#regla: para generar "ejecutable" uso "main.c", lo que está debajo es el comando (siempre con un tab)
programa: main.c
	@echo "Compilando.."
	gcc main.c -o programa

#regla clean, no tiene dependencias, borra el ejecutable
clean: 
	rm programa

#Proceso desede el programa al binario
	#Programa
		#Compliacion (genera los .o objetos)
		#Enlace (linkeo)
	#Binario

#Dependencias
	#Regla: [dependencias] las dependencias son opcionales
	#-TAB- comando  (si cumple hace el comando)


run: programa
	./programa

	






